# Generated by Django 4.2.4 on 2024-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
