# Generated by Django 4.2.2 on 2023-06-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('declined', 'Declined')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
