# Generated by Django 4.2.2 on 2023-06-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_company_options_alter_jobposting_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='declined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('declined', 'Declined')], default='', max_length=10),
        ),
    ]
