# Generated by Django 4.2.2 on 2023-06-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_jobposting_initial_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='initial_contact_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
