# Generated by Django 4.2.2 on 2023-06-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_jobposting_initial_contact_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='declined_days',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='initial_contact_days',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
