# Generated by Django 4.2.2 on 2023-06-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_jobposting_declined_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='declined_date',
            new_name='sorry_passed_date',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='declined_days',
            new_name='sorry_passed_days',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('passed', 'Passed')], default='', max_length=10),
        ),
    ]
