# Generated by Django 4.2.2 on 2023-06-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_rename_declined_date_jobposting_sorry_passed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='sorry_passed_date',
            new_name='declined_date',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='sorry_passed_days',
            new_name='declined_days',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('declined', 'Declined')], default='', max_length=10),
        ),
    ]
